### ISSUE TITLE
#team-106-the-kingsnakes

### ISSUE THREAD

**Issue by chelmerrox** [krys2fa/js-tic-tac-toe#2]
Hey Chris!

You've done a wonderful presentation today & your project is looking great so far!

- great job on fixing the issues from yesterday
- your code & logic is well thought out. Nice job on this!
- you can probably take the condition in the if statement used in checkWin function and store it in a variable instead. It would be a little more readable.
- since you've separated your DOM logic and application logic into their own files, you can further separate some code in your application logic/file that might belong in the DOM file (eventListeners, etc) and vice versa.

Your project also looks good for submission! All the best with this. 😃👍🏽

**Comment by krys2fa** [comment]
Thanks Losa et al! 😃
